version: '3.1'

services:
  node:
    build:
      context: .
      args:
        http_proxy: http://t0000104:12345678@192.168.50.140:8080
        https_proxy: http://t0000104:12345678@192.168.50.140:8080
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229
    ports:
      - "4033:4033"
      - "5858:5858"
      - "9229:9229"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
